// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package txx.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\ttxx.proto\"\035\n\tMyRequest\022" +
      "\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realn" +
      "ame\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005" +
      "\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age" +
      "\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"J\n\023StudentResponseL" +
      "ist\0223\n\017studentResponse\030\001 \003(\0132\032.txx.proto" +
      ".StudentResponse\"%\n\rStreamRequest\022\024\n\014req" +
      "uest_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rres" +
      "ponse_info\030\001 \001(\t2\306\002\n\016StudentService\022F\n\025g" +
      "etRealNameByUserName\022\024.txx.proto.MyReque" +
      "st\032\025.txx.proto.MyResponse\"\000\022M\n\020getStuden" +
      "tsByAge\022\031.txx.proto.StudentRequest\032\032.txx" +
      ".proto.StudentResponse\"\0000\001\022X\n\027getStudent" +
      "WrapperByAges\022\031.txx.proto.StudentRequest" +
      "\032\036.txx.proto.StudentResponseList\"\000(\001\022C\n\006" +
      "biTalk\022\030.txx.proto.StreamRequest\032\031.txx.p" +
      "roto.StreamResponse\"\000(\0010\001B\033\n\ttxx.protoB\014" +
      "StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_txx_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_txx_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_txx_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_txx_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_txx_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_txx_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_txx_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_txx_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_txx_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_txx_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_txx_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_txx_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_txx_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_txx_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
