// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package txx.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_txx_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_txx_proto_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\ttxx.proto\"\035\n\tMyRequest\022" +
      "\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realn" +
      "ame\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005" +
      "\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age" +
      "\030\002 \001(\005\022\014\n\004city\030\003 \001(\t2\247\001\n\016StudentService\022" +
      "F\n\025getRealNameByUserName\022\024.txx.proto.MyR" +
      "equest\032\025.txx.proto.MyResponse\"\000\022M\n\020getSt" +
      "udentsByAge\022\031.txx.proto.StudentRequest\032\032" +
      ".txx.proto.StudentResponse\"\0000\001B\033\n\ttxx.pr" +
      "otoB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_txx_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_txx_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_txx_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_txx_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_txx_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_txx_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_txx_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_txx_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_txx_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
